# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9d67f825964b627f01856a4bce01621a7df0d1d2140b8da7a9831a0a3384ac0246a7cfc19816d658e8ff2fc30374261d019091554a4b81e40a1fa3268c8bdcd

test:
  secret_key_base: 3386730e3607b1b0e6146b2b509745a3d48511fc11b67ff1a5900ce459582b16abb1d441e4056f6c9e2049f0ac7e798d4ba793e087134b9bc41221c3de9e1b1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
